### ISSUE TITLE
As a user I want to have access to the aggregated data values being used in the visualization

### ISSUE THREAD

**Issue by ptitzler** [pixiedust/pixiedust#273]
PD performs aggregations based on the selected visualization options. As a user I would like to have the ability to see the aggregated data points.

**Comment by vabarbosa** [comment]
@ptitzler if you run `display` with the additional `debug=True` parameter, it creates an additional dataFrame (i.w., `workingPDF`) which the data used for visualization. for example:

![image](https://user-images.githubusercontent.com/13156555/44619260-8a3ef800-a851-11e8-90f3-54c573827258.png)

is this what you are looking for? if so, mind closing this or expand further on what you are requesting. thank you.
