### ISSUE TITLE
display() barchart - matplotlib: legend is not displayed

### ISSUE THREAD

**Issue by ptitzler** [pixiedust/pixiedust#289]
1.0.2+

Input data set: <string1>,<string2>,<numeric>
* chart type: bar chart
* options > keys: &lt;string1&gt;
* options > values: &lt;string2&gt;
* options > aggregations: COUNT
* renderer: matplotlib
* cluster by: &lt;string2&gt;
* type: grouped
* legend: checked

### Expected behavior
A legend is displayed for each grouping

### Actual behavior
No legend is displayed

**Comment by vabarbosa** [comment]
@ptitzler you can no longer `Cluster By` a column you entered for either `Keys` or `Values`. 
currently, when you do `Cluster By` a third column, the legend is shown for the groupings. for example:

![image](https://user-images.githubusercontent.com/13156555/44619451-9082a380-a854-11e8-81fb-71a77849e5bb.png)

i am closing this. please re-open if you still have concerns.
