### ISSUE TITLE
As a mentor, I want to be able to have people attending a workshop to generate maps without creating a mapbox account and using a mapbox access token

### ISSUE THREAD

**Issue by aklson-datascientist** [pixiedust/pixiedust#333]
### Expected behavior
It would be great if PixieDust is a self-contained library where one can create a map without the need to create an account on mapbox and using their mapbox access token.

### Actual behavior
To generate a map, one has to create a mapbox account and use their mapbox access token.

**Comment by rajrsingh** [comment]
This is not the case anymore. Pixiedust has a built-in Mapbox token.
