### ISSUE TITLE
For MapBox maps, change or remove requirements for Values field

### ISSUE THREAD

**Issue by ulemanstreaming** [pixiedust/pixiedust#460]
## As a data scientist, I want to put geospatial feature data on a map and show arbitrary fields (attributes) so that I can understand spatial relationships and access individual feature information.
See also [issue #459](https://github.com/ibm-watson-data-lab/pixiedust/issues/459): preserveCols is an interim step, since it is already partially implemented.

### Expected behavior
In the Options dialog, I can choose or list attributes to be displayed in hover popups on the map. In the current dialog layout, the Values box can be used for that.

### Actual behavior
The Values box is restricted to numeric columns only. This makes sense for normal charts but is an arbitrary and inappropriate restriction for maps.

### Steps to reproduce the behavior
Take any geospatial data and use display() to create a MapBox map. It is impossible to drag a non-numeric column into the Values box.

**Comment by rajrsingh** [comment]
_may require over-riding a lot of existing base class methods_

**Comment by rajrsingh** [comment]
related to #203

**Comment by vabarbosa** [comment]
this specific issue has been indirectly addressed by the work done for #562
the `Values` field in the Options dialog is no longer limited to just numeric columns

**Comment by rajrsingh** [comment]
Fixed in https://github.com/ibm-watson-data-lab/pixiedust/tree/mapbox-v2
