### ISSUE TITLE
default aggregation function varies by renderer

### ISSUE THREAD

**Issue by ptitzler** [pixiedust/pixiedust#612]
PixieDust 1.1.7.1

```
pandas_df = pixiedust.sampleData("https://openobjectstore.mybluemix.net/misc/milliondollarhomes.csv", forcePandas = True)

display(pandas_df, debug = True)
workingPDF

display(pandas_df, debug = True)
workingPDF
```

Configure the first chart as follows:
 - bar chart
 - aggregation AVG
 - keys: BEDS
 - values: PRICE
- limit 1000 rows
- renderer matplotlib

Configure the first chart as follows:
 - bar chart
 - aggregation AVG
 - keys: BEDS
 - values: PRICE
- limit 1000 rows
- renderer <choose any other renderer>

 inspect the `workingPDF` and note how the values differ. It appears that an aggregation other than AVG is used.

I have not tried to find out whether the same problem exists for other chart types.

**Comment by rajrsingh** [comment]
Is the name of this issue good @ptitzler? Varying the default aggregation by renderer is a feature not a bug.

**Comment by ptitzler** [comment]
It is. If you follow the scenario you'll notice that the displayed aggregation option is "AVG". However, the applied aggregation option is something different. [That's the bug.]

I do think it makes sense to use the same default aggregation function. As a user I would not expect calculations to change if I switch between renderers (for the same chart type).

**Comment by rajrsingh** [comment]
OK so 2 problems:
1. the applied aggregation doesn't match the one specified in metadata
2. the applied aggregation changes when the renderer changes

It could still be OK for a renderer to apply it's own default aggregation when none exists in metadata...

**Comment by ptitzler** [comment]
Actually the metadata does not include the aggregation property unless one explicitly selects an aggregation. so issue 1) is really that the UI display does not reflect the renderer's default. 

I wouldn't agree that renderers should be allowed to define what their default aggregation is for two reasons:
* A renderer's task is to visualize the workingPDF (which represents the aggregated data). A renderer should not modify the workingPDF.
 * If renderers were allowed to define their own default aggregation a user would have to be alerted to the fact that the `workingPDF` has implicitly changed. This change (if we were to allow it) is not obvious because one would have to open the chart options to learn what the new aggregation method is. 

What benefits would be provided if renderers were free to choose their own default aggregation method instead of adhering to the one that is defined in the chart options?

**Comment by rajrsingh** [comment]
In `baseChartDisplay.py` there's a `getDefaultAggregation` method that returns "SUM". In `pieChartDisplay.py` that method is overridden. It returns "COUNT". This is the only place I see a conflict with the default aggregation. How's this for a clarification of the issue @ptitzler:
1. The default aggregation method should be "COUNT" (so that it will work with non-numerics)
1. No class should override the default. 
1. Options UI should check metadata for the aggregation method, then fall back to what is returned by the `getDefaultAggregation` method

**Comment by ptitzler** [comment]
There's more to it. If you run the following notebook without making any changes
[visualize_data.zip](https://github.com/ibm-watson-data-lab/pixiedust/files/1759893/visualize_data.zip) you'll notice the difference.
