### ISSUE TITLE
display(): add support for None as a filter condition

### ISSUE THREAD

**Issue by ptitzler** [pixiedust/pixiedust#643]
PD 1.1.8

As a user, I want to identify fields that are undefined in my dataframe.

### Expected behavior
- The filter widget allows for selection of `None` as a comparison value.

### Workaround
 - replace `None` with a well-known string in the DF before calling `display()`

### Steps to reproduce the behavior
 - Create a DF that contains one or more None values.

**Comment by vabarbosa** [comment]
@ptitzler please review PR #654 and see if it satisfies your requirements.

**Comment by DTAIEB** [comment]
@ptitzler @vabarbosa being able to show only rows with missing values is great, but how would someone show only rows that don't have missing value?

**Comment by vabarbosa** [comment]
@DTAIEB, @ptitzler would be better at explaining when/how he intends and thinks is best for the functionality. in the case, of the Filter i believe you could probably use the regex and for numberic fields use something an expression like: _column greater than \<some value less than the minimum\>_.  

for the table view, i have updated to include options to show for all rows, rows with missing values, or rows without missing values.

![image](https://user-images.githubusercontent.com/13156555/37525004-f6736896-2901-11e8-9ac0-670d3561e676.png)
