### ISSUE TITLE
Display() - histogram options cannot be applied

### ISSUE THREAD

**Issue by ptitzler** [pixiedust/pixiedust#661]
PD 1.1.9

### Steps to reproduce the behavior
* Create a dataframe containing at least one numeric field
* Invoke `display()` and select the histogram chart type
* Select the numeric field as **Values**
* Try to apply the option

Actual behavior:
 * Nothing happens

Expected behavior:
 * Options are applied

**Comment by vabarbosa** [comment]
@ptitzler @DTAIEB PR #662
