### ISSUE TITLE
Return from pixiedust.enableJobMonitor() spelled incorrectly

### ISSUE THREAD

**Issue by jamesyarrington** [pixiedust/pixiedust#671]
Using Version 1.1.9

I ran into this while testing something else, I figured I'd let you all know.  I can't imagine this would be a high priority issue.

### Expected behavior
For the command, `pixiedust.enableJobMonitor()`
The response printed to std out should be:
> Succe**ss**fully enabled Spark Job Progress Monitor

### Actual behavior
The actual response is:
> Succe**s**fully enabled Spark Job Progress Monitor

_(There is a missing 's')_
### Steps to reproduce the behavior
Send the commands:
```python
import pixiedust
pixiedust.enableJobMonitor()
```

**Comment by DTAIEB** [comment]
@jamesyarrington thank you for the feedback, feel free to submit a PR with the fix. If not, we'll fix it for 1.1.10.
