### ISSUE TITLE
jupyter lab  

### ISSUE THREAD

**Issue by jmbertoncelli** [pixiedust/pixiedust#679]
Hello,

I did install pixiedust  but because of JavaScript output is disabled in JupyterLab I cannot leverage
display and progress bar...

any idea or does pixiedust not ready yet for jupyter lab?

thanks

JM

**Comment by DTAIEB** [comment]
@jmbertoncelli PixieDust does not yet support Jupyter Lab, It's on the backlog but we don't have an ETA yet.

**Comment by fperez** [comment]
It seems this is a duplicate of #613, perhaps better to close here and focus discussion over there?

**Comment by DTAIEB** [comment]
Agreed, closing this ticket
