### ISSUE TITLE
PySparkDataFrameDataHandler not defined

### ISSUE THREAD

**Issue by dautovri** [pixiedust/pixiedust#680]
display(v) , where  v  spark Dataframe

### Actual behavior
NameError: global name 'PySparkDataFrameDataHandler' is not defined

Pixiedust version 1.1.10

**Comment by DTAIEB** [comment]
@dautovri do you have a code snippet we can use to reproduce the error?
If not, can you please run the following command in a separate cell:
%pixiedustLog -l debug
and paste the traceback
Thanks

**Comment by dautovri** [comment]
```
2018-05-22 09:51:32,976 - pixiedust.utils.storage - INFO - No change in version: 1.1.10 -> 1.1.10.
2018-05-22 09:51:34,424 - pixiedust.display.chart - WARNING - Unable to import renderer brunel: No module named 'brunel'
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-7148be4422cd> in <module>()
      1 get_ipython().magic('pixiedustLog -l debug')
----> 2 display(e)

/opt/anaconda3/lib/python3.6/site-packages/pixiedust/display/__init__.py in display(entity, **kwargs)
    108 
    109             #get a datahandler and displayhandler for this entity
--> 110             dataHandler = getDataHandler(kwargs, entity)
    111             selectedHandler = getSelectedHandler(kwargs, entity, dataHandler)
    112 

/opt/anaconda3/lib/python3.6/site-packages/pixiedust/display/datahandler/__init__.py in getDataHandler(options, entity)
     29 def getDataHandler(options, entity):
     30     if dataFrameMisc.isPySparkDataFrame(entity):
---> 31         return PySparkDataFrameDataHandler(options, entity)
     32     elif dataFrameMisc.isPandasDataFrame(entity):
     33         return PandasDataFrameDataHandler(options, entity)

NameError: name 'PySparkDataFrameDataHandler' is not defined
```

**Comment by dautovri** [comment]
![image](https://user-images.githubusercontent.com/4597187/40371891-1563e6ba-5e16-11e8-92e6-557610ed3599.png)

**Comment by DTAIEB** [comment]
@dautovri Thank you for the info, this is helpful.
In a new cell, can you please run the following:
```
from pixiedust.utils.shellAccess import ShellAccess
from pyspark import SparkContext
print(ShellAccess["sc"] is not None or ShellAccess["spark"] is not None)
```
It's the code used by Environment.hasSpark, and I need to know which of the line above is failing for you

**Comment by JiuxinZhang** [comment]
I met same issue and solved by:
1. Relaunch jupyter notebook
2. Do not import pixiedust and display(your_table)
3. Import pixiedust and display(your_table)
Then this error will be solved.
I don't know why, maybe this handler is defined by Ipython built-in display() function?

**Comment by markwatsonatx** [comment]
I believe I have encountered this the pixiedust import comes before my SparkContext is initialized. When I move the import after SparkContext initialization it seems to fix it. I am using a Jupyter Docker stack container.

**Comment by rahulbhat44** [comment]
"import pixiedust" after importing the data and it will work
