### ISSUE TITLE
pixie_debugger does not work with %pylab

### ISSUE THREAD

**Issue by gergol** [pixiedust/pixiedust#704]
I'm heavily making use of the %pylab magic in my jupyter notebooks. 

### Expected behavior
%%pixie_debugger should work in a notebook with loaded %pylab environment.

### Actual behavior
When executing a cell containing %%pixie_debug in a notebook with %pylab environment, the following exception is thrown:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-0bbddd03d5df> in <module>()
----> 1 display(PixieDebugger_instance,nostore_pixieapp='PixieDebugger_instance',nostore_ispix='true',runInDialog='false',handlerId='pixiedust.apps.debugger.pixieDebugger_PixieDebugger_id',cell_id='8f9c752f5c534904be4db6f6eab75ec5',nostore_pixiedust='true',nostore_cw='1098',nostore_vh='1065',showchrome='true',org_params='nostore_pixieapp,nostore_ispix,runInDialog,handlerId,nostore_pixiedust')

~/.virtualenvs/pixietest/lib/python3.6/site-packages/IPython/core/display.py in display(include, exclude, metadata, transient, display_id, *objs, **kwargs)
    303                 # kwarg-specified metadata gets precedence
    304                 _merge(md_dict, metadata)
--> 305             publish_display_data(data=format_dict, metadata=md_dict, **kwargs)
    306     if display_id:
    307         return DisplayHandle(display_id)

~/.virtualenvs/pixietest/lib/python3.6/site-packages/IPython/core/display.py in publish_display_data(data, metadata, source, transient, **kwargs)
    118         data=data,
    119         metadata=metadata,
--> 120         **kwargs
    121     )
    122 

TypeError: publish() got an unexpected keyword argument 'nostore_pixieapp'
```

### Steps to reproduce the behavior
Create a notebook with two cells:
Cell 1: 
```
%pylab
import pixiedust
```
Cell 2:
```
%%pixie_debugger
a = 4
```
Cell 2 will fail to complete.

**Comment by DTAIEB** [comment]
The issue comes from the fact that %pylab is defining the "display" variable first before pixiedust does it. In this case, pixiedust will not override and leave the display variable defined as it is, causing the issue with the PixieDebugger PixieApp which is trying to use the display variable. I've provided a fix that detects this situation and uses the fully qualified "pixiedust.display" name instead.
Note: if you want to use the pixiedust display function, you'll need to fully qualify as well.
