### ISSUE TITLE
Cannot exit a debug session while debugging

### ISSUE THREAD

**Issue by jacquelo** [pixiedust/pixiedust#724]
As a user, I want to exit the debugger in the middle of the debug session while it is still debugging. This is important if I'm debugging a cell that has an infinite loop. If I ran the cell normally, the kill command would stop anything running. But while in the debug session, the kill command just sends an interrupt to the debugger and the debugger does not complete or exit.

### Expected behavior
Kernel stop/ kill button should exit debug session (or interrupt on first press and then kill it on the second one)

### Actual behavior
Interrupts and just keeps interrupting without exiting

### Steps to reproduce the behavior
Write a program with an infinite loop and try to exit from that debug session

**Comment by DTAIEB** [comment]
@jacquelo This looks like a duplicate of #689, can you please confirm?

**Comment by jacquelo** [comment]
Yes. This looks to be the same issue. Is there a current branch for 1.1.12 that I can test this feature or is it closed as an issue because there is a plan to fix it on the next release? Any eta on that? The 1.1.12 page says no but I'm just wondering. Thanks again!
