### ISSUE TITLE
if `PIXIEDUST_HOME`  is defined then use `PIXIEDUST_HOME + data/libs` (this would be for local install, etc) else if `PIXIEDUST_LIBS_PATH` is defined use it as is else default to `~/data/libs`.

### ISSUE THREAD

**Issue by shobhit0511** [pixiedust/pixiedust#730]
if `PIXIEDUST_HOME`  is defined then use `PIXIEDUST_HOME + data/libs` (this would be for local install, etc) else if `PIXIEDUST_LIBS_PATH` is defined use it as is else default to `~/data/libs`.

**Comment by vabarbosa** [comment]
this is related to #492, where in environments that `PIXIEDUST_HOME` is not defined and there is no access to `~/data/libs` the `installPackage` function fails

**Comment by shobhit0511** [comment]
https://github.com/pixiedust/pixiedust/pull/732/files
